spring:
  jmx:
    enabled: false
  main:
    lazy-initialization: false # Needed false for running MappingRuleLoaderService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    generate-unique-name: true

security:
  authentication:
    header: Authorization
    apikey: Bearer local-secret
